kittiu/lpp

lpp/custom/purchase_order.py, lpp/hooks.py, lpp/public/js/purchase_invoice.js, lpp/public/js/stock_entry.js
- Feature #5607 PurInv-เพิ่มฟิล PO No. ( เพิ่มเติมจาก requirement เดิม )
- Feature #5600 MatReq-ตอนสร้างถ้าเลือก purpose แล้วให้ auto เลือก series name ( change series name )
=> Additional Feature #5607 ,  Feature #5600 

lpp/hooks.py, lpp/public/js/payment_entry.js
ข้อ 52 : ในตาราง Payment entry เพิ่มยอดก่อน Vat นำมาแสดง
=> [Edited]: Payment Entry

lpp/lpp/report/annual_sale_report/annual_sale_report.js, lpp/lpp/report/annual_sale_report/annual_sale_report.json, lpp/lpp/report/annual_sale_report/annual_sale_report.py, lpp/lpp/report/annual_sale_report/quarter.py
Q1 (Quarter 1): มกราคม - มีนาคม
Q2 (Quarter 2): เมษายน - มิถุนายน
Q3 (Quarter 3): กรกฎาคม - กันยายน
Q4 (Quarter 4): ตุลาคม - ธันวาคม
Filter Year, Code, Customer, Product
Doctype: Sales Order
=> Annual Sale Report (Quarter)

lpp/lpp/report/annual_sale_report/annual_sale_report.js, lpp/lpp/report/annual_sale_report/annual_sale_report.py, lpp/lpp/report/annual_sale_report/monthly.py
- Filter Type
- Doctype: Sales Order
=> [Added]: Annual Sale Report (Monthly)

lpp/lpp/report/annual_sale_report/monthly.py
- ปรับรูปแบบของ Credit Note ให้เหมือนกับ Sales Order
=> [Edited]: Annual Sale Report (Monthly)

lpp/lpp/report/annual_sale_report/monthly.py, lpp/lpp/report/annual_sale_report/quarter.py
- เพิ่ม customer_group, total_customer_group
- เพิ่ม filter customer_group
=> [Edited] : Annual Sale Report (Monthly)

lpp/public/js/item.js
- Batch No default ตาม Item Group 1 เฉพาะประเภท Product,  Raw Material
=> [Edited]: Item

lpp/custom/custom_purchase_receipt.py, lpp/hooks.py
=> [Edited] : Purchase Receipt

lpp/lpp/patches/remove_field_from_qoutation.py, lpp/patches.txt
- เขียน patch ลบฟิล custom_customer_group
=> [Edited] : Patches

lpp/lpp/patches/remove_field_from_quotation_20241015_1700.py
- เพิ่ม type except เพื่อดัก error
=> [Edited]: Patches

lpp/lpp/patches/remove_field_from_journal_entry_20241016_1130.py
- แก้ไฟล์ remove field from journal entry ให้ล้างข้อมูลในฟิลด์ก่อนลบฟิลด์
=> [Fixed]: Patches Journal Entry

lpp/custom/custom_purchase_receipt.py, lpp/custom/purchase_order.py
- remove unuse in purchase reciept & purchase order
=> Refactor Code Purchase Order , Purchase Reciept

lpp/custom/custom_item.py, lpp/lpp/doctype/item_molds_detail/item_molds_detail.js, lpp/lpp/doctype/item_molds_detail/item_molds_detail.json, lpp/lpp/doctype/item_molds_detail/test_item_molds_detail.py, lpp/lpp/patches/clear_and_trim_item_molds_detail_20241018_1120.py, lpp/patches.txt, lpp/public/js/work_order.js
=> Dev feature daris

lpp/public/js/job_card.js
-  Set ให้การส่งของระหว่าง Station จำนวนสินค้า station  ใหม่ ต้อง <= จำนวนสินค้า station ก่อนหน้า //ยกเว้น Station สุดท้าย Job card แรก สามารถผลิตเกินได้
=> [Edited]: Job Card

lpp/lpp/report/product_report/product_report.js, lpp/lpp/report/product_report/tape_and_protective_band.py, lpp/lpp/report/product_report/tray_and_reel.py
=> [Edited] : Product Report

lpp/public/js/quality_inspection.js
- แก้ไขบัคตาราง Quality Inspection ไม่สามารถเซฟได้
=> [Edited] :  fix quality inspection table

lpp/custom/material_request.py
=> [Edited]: MaterialRequest Save แล้ว Customer ที่เลือกไปหาย

lpp/lpp/doctype/quality_inspection_order/quality_inspection_order.json, lpp/lpp/patches/remove_field_from_quality_inspection_order_20241106_1740.py, lpp/patches.txt
Tolerance (+) tolerance_upper
Tolerance (-) tolerance_lower
=> [Edited]: QA add

lpp/custom/custom_pricing_rule.py, lpp/custom/custom_quality_inspection.py, lpp/lpp/doctype/quality_inspection_order/quality_inspection_order.json, lpp/public/js/quality_inspection.js
- แก้ไข Running No. จากเดิมใช้เป็น Running 5 หลัก ปรับเป็น 2 หลักเท่านั้น ( Pricing Rule )
-  change tolerance_max to tolerance_upper and tolerance_min to tolerance_lower
=> Fix QA Defect

lpp/custom/quotation.py, lpp/public/js/item.js, lpp/public/js/sales_order.js
- ข้อ 38 กด Get item from ต้องนำมาให้ที่หน้านี้ด้วยจากหน้า Quotation
- ข้อ 37 Asset Naming Series ให้แสดงเมื่อทำการเลือก Asset catagory (เหมือนหน้า Asset)
=> Fixed Defect UAT ( 38  , 37 )

lpp/lpp/report/purchase_tax/purchase_tax.py, lpp/lpp/report/sales_tax/sales_tax.py
Purshase Tax
- ปรับการแสดงข้อมูลสาขา
- ลบการ Group ข้อมูล
- ปรับการแสดงข้อมูลเลขที่ใบกำกับภาษี
Sales Tax
- ปรับการแสดงข้อมูลสาขา
=> [Edited]: update data by report purchase_tax , sales_tax
